### ISSUE TITLE
Meetup Page displays our upcoming events

### ISSUE THREAD

**Issue by Andy-TE** [code-mentoring/code-mentoring.github.io#19]
Add an emdeded link showing the upcoming for code metnors

**Comment by TomoyaKuroda** [comment]
Probably we can use this API https://www.meetup.com/meetup_api/docs/:urlname/events/#list

**Comment by ghost** [comment]
Great idea to have a dynamic list of upcoming events, this could be embedded in the Meetup page.

We might need tabs or something to separate each city.

**Comment by edgul** [comment]
As Tomoya and I have discovered to do this free of cost we will need to implement our own CORS proxy server. Not a huge deal, but we need to first think about our own backend hosting for this. 

Attempts to solve CORS so far: 
* Tomoya's code for pr 31 works if you enable CORS heroku proxy (but this is a developer hack)
* Directly querying the meetup api will require user login (we don't want to demand every user login just to see our events)
* Github pages has no support for backend extension
* Vercel serverless proxy with code-mentoring repo will require paid subscription.

**Comment by TomoyaKuroda** [comment]
It seems we can achieve this with JSONP. I'll push my update

**Comment by TomoyaKuroda** [comment]
@edgul @shaneSheridan I think we can close this issue with this pull request https://github.com/code-mentoring/code-mentoring.github.io/pull/31

**Comment by edgul** [comment]
I'd say so.
