### ISSUE TITLE
Setup remote server hosting

### ISSUE THREAD

**Issue by edgul** [code-mentoring/code-mentoring.github.io#34]
To enable more advanced functionality we need to have our own remote server.

Since github pages offers no way to extend into backend. We will need to do this ourselves.
This will allow functionality like:
* Dynamic meetup events (via CORS proxy)

**Comment by TomoyaKuroda** [comment]
@edgul I think we can close this issue with this pull request https://github.com/code-mentoring/code-mentoring.github.io/pull/31

**Comment by edgul** [comment]
You are correct!

**Comment by edgul** [comment]
If this becomes useful for other functionality we will revisit this idea
