### ISSUE TITLE
Hyper link in README.md does not work

### ISSUE THREAD

**Issue by ghost** [code-mentoring/code-mentoring.github.io#5]
_Steps to reproduce the problem_

1. Go to README.md
2. Click on hyper link to the live (production) website

_Result_
404 error, website not found.

_Expectation_
Opens the Code Mentoring site `https://code-mentoring.github.io/`

**Comment by pagliuca523** [comment]
Problem Fixed:

-Did a pull request for the correction of the file.
-There was a problem with the missing char "-".
-Tested and should work normally.

**Comment by edgul** [comment]
Works! Merged
